create table public.avaliacoes (
  id bigint generated by default as identity not null,
  id_produto bigint not null,
  id_cliente bigint not null,
  nota integer not null check (nota >= 1 and nota <= 5),
  comentario text,
  created_at timestamp with time zone not null default now(),
  constraint avaliacoes_pkey primary key (id),
  constraint avaliacoes_id_produto_fkey foreign key (id_produto) references produtos (id),
  constraint avaliacoes_id_cliente_fkey foreign key (id_cliente) references clientes (id),
  constraint avaliacoes_id_produto_id_cliente_key unique (id_produto, id_cliente)
) TABLESPACE pg_default;