create table public.clientes (
  id bigint generated by default as identity not null,
  nome text not null,
  email text not null,
  endereco text not null,
  created_at timestamp with time zone not null default now(),
  telefone text not null,
  constraint clientes_pkey primary key (id),
  constraint clientes_email_key unique (email),
  constraint clientes_telefone_key unique (telefone)
) TABLESPACE pg_default;