create table public.pedidos (
  id bigint generated by default as identity not null,
  id_produto bigint null,
  id_cliente bigint null,
  constraint pedidos_pkey primary key (id),
  constraint pedidos_id_cliente_fkey foreign KEY (id_cliente) references clientes (id),
  constraint pedidos_id_produto_fkey foreign KEY (id_produto) references produtos (id)
) TABLESPACE pg_default;