create type public.status_pedido as enum ('pendente', 'entregue', 'cancelado');

create type public.forma_pagamento as enum ('cartao_credito', 'boleto', 'pix');

create table public.pedidos (
  id bigint generated by default as identity not null,
  id_produto bigint null,
  id_cliente bigint null,
  status public.status_pedido not null default 'pendente',
  quantidade integer not null check (quantidade > 0),
  total numeric(10,2) not null check (total >= 0),
  forma_pagamento public.forma_pagamento not null default 'cartao_credito',
  created_at timestamp with time zone not null default now(),
  constraint pedidos_pkey primary key (id),
  constraint pedidos_id_cliente_fkey foreign KEY (id_cliente) references clientes (id),
  constraint pedidos_id_produto_fkey foreign KEY (id_produto) references produtos (id)
) TABLESPACE pg_default;





