create table public.produtos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome text not null,
  descricao text not null,
  valor numeric not null,
  imagem text not null,
  constraint produtos_pkey primary key (id)
) TABLESPACE pg_default;
