create table public.senhas (
  id bigint generated by default as identity not null,
  id_cliente bigint not null,
  senha text not null,
  constraint senhas_pkey primary key (id),
  constraint senhas_id_cliente_fkey foreign key (id_cliente) references clientes (id),
  constraint senhas_id_cliente_key unique (id_cliente)
) TABLESPACE pg_default;